/**
 * This module contains action types.
 *
 * @format
 * @flow
 */

export const CHANGE_COMMENT_INPUT_VISIBILITY =
  'CHANGE_COMMENT_INPUT_VISIBILITY';
export const FETCH_PRODUCT_COMMENTS_FAIL = 'FETCH_PRODUCT_COMMENTS_FAIL';
export const FETCH_PRODUCT_COMMENTS_SUCCESS = 'FETCH_PRODUCT_COMMENTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const OPEN_PRODUCT_INFO = 'OPEN_PRODUCT_INFO';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESTORE_SESSION_FAIL = 'RESTORE_SESSION_FAIL';
export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS';
export const SET_COMMENTS_NOT_LOADED = 'SET_COMMENTS_NOT_LOADED';
